<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <AssemblyName>Jarvis.VisualEffects</AssemblyName>
    <RootNamespace>Jarvis.VisualEffects</RootNamespace>
  </PropertyGroup>
</Project>
